### ISSUE TITLE
Let's promote this?

### ISSUE THREAD

**Issue by LappleApple** [zalando/banknote#2]
Hey--several people have commented on this project/how cool it is. If I'm not mistaken/missing something it's useful out-of-the-box to non-Zalandos. So, let's promote? I can do the README and promo ... if you want other resources, LMK and we can try to make something happen during the FOSS Clinic (March 4, all day).

**Comment by aryszka** [comment]
yes! it's a real proper piece of code :)

**Comment by LappleApple** [comment]
OK, let's set up 20 minutes to collect all the README essentials. You got time today/Friday?

**Comment by aryszka** [comment]
so... i was out-of-office on Friday. But anyway, I think we should wait for Dmitriy with this, because this is really his code, and I only made some nitpicking changes to the readme. I think Dima is back from his vacation next week.

**Comment by LappleApple** [comment]
Sounds good! I've got plenty to work on :)
