### ISSUE TITLE
Could not install with NPM

### ISSUE THREAD

**Issue by xolvo** [zalando/banknote#7]
I'm trying to install this lib with command:

```
npm i -s banknote
```

but I get following error:

```
├── UNMET PEER DEPENDENCY babel-core@^6.0.0
├── banknote@0.2.1
└── UNMET PEER DEPENDENCY webpack@2.4.1
```

Node version: v7.9.0
NPM version: 4.2.0

**Comment by grassator** [comment]
@xolvo Works for me, at least in an empty repo, and also the output that you have shows that banknote installed successfully. Judging by the fact that it doesn't depend on either of those packages I assume that there is an error somewhere else in your package.json.
